language: php

services: mongodb

php:
  - 5.3
  - 5.4

before_script:
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: php index.php testing test

notifications:
  irc: "irc.esper.net#axxim"
